### PR TITLE
Refactor Feedback

### PR DESCRIPTION
**Pull request by timoludwig**
### Short description

This adds all kinds of improvements for the feedback functionality and some improvements under the hood.
Also, this should enable the feedback list to get pagination (see #660).

### Proposed changes

- Generalize filter form scripts
- Generalize bulk actions
- Refactor feedback models, views and templates 
- Add bulk actions to feedback list 
- Add filters to feedback list 

### Resolved issues

Fixes: #600

Screenshot_2021-02-19 Integreat CMS

### CODE REVIEW

**Comment by ulliholtgrave** [comment]
Unfortunately I won't really be able to provide a completet feedback, but I found a few UI problems/bugs. 
Feedback-Bugs
Firstly: The table has a strange border on the left side. As this is different from the other tables we should remove this or apply this styling to the other tables.
Secondly, you gave the negative-vote a left-padding of .25em. If there are only negative votes this results in placeholder. I propose, that you add a if-clause checking whether there are any positive votes and apply either pl-r or pl-l.

**Comment by timoludwig** [comment]
> Firstly: The table has a strange border on the left side. As this is different from the other tables we should remove this or apply this styling to the other tables.

I liked the left border on unread feedback in WordPress, so I tried to recreate it.
Screenshot_2021-02-22 Kommentare (9) ‹ Testumgebung — WordPress
Unfortunately, I couldn't get the checkboxes of the read entries lined up without the border on the gray rows, so I just added the border on all rows. I see two options now:

1) Completely remove the left border
2) Try further to remove the border on gray rows and only show it on the highlighted rows. I mean, somehow it has to work :grin: 

What would you prefer?

**Comment by ulliholtgrave** [comment]
I guess, what bothers me the most is the border at the table header. The rest is fine for me :)

**Comment by timoludwig** [comment]
I added the following changes to this PR:
- Make left border bold only when feedback is unread
- Align positive and negative feedback, even if only one of both is given
- Add pagination for feedback
- Add feedback for POIs and the map incl. new API endpoints
- Remove the possibility to add the base feedback objects in admin.py and add the possibility to create all submodels
- Change feedback `read` flag to `read_by` field containing the user who marked the feedback as read

**Review by ulliholtgrave — APPROVED** [review]
Looks reasonable to me :) We might wanna do some small improvements to the UI of the feedback lists, but this is ready to ship for now :+1:

**Comment by timoludwig** [comment]
I added some more minor improvements:
- Hover effect in the feedback list
- The possibility to select/deselect the checkbox on a row by clicking anything in the row which isn't a link
- The displayed object name now always uses the name of the current backend language if available and the region's default language as fallback
- The rating is not represented with "Positive" or "Negative" anymore, but the thumbs icons directly

@ulliholtgrave if you are fine with these changes, I will merge this PR.

**Pull request merged**
