### PR TITLE
Improve views documentation

### PR DESCRIPTION
**Pull request by svenseeberg**
Modules:
* [x] analytics
* [x] authentication
* [x] dashboard
* [x] error_handler
* [x] events
* [x] language_tree
* [x] languages
* [x] media
* [x] offer_templates
* [x] offers
* [x] organizations
* [x] pages
* [x] pois
* [x] push_notifications
* [x] regions
* [x] roles
* [x] settings
* [x] statistics
* [x] users

Fixes: #326

### CODE REVIEW

**Comment by svenseeberg** [comment]
@jnugh @ulliholtgrave could you please comment on the doc changes to `src/cms/views/authentication/authentication_actions.py`?

**Comment by ulliholtgrave** [comment]
As far as I can see, you mainly adjusted the docstrings. From my perspective this looks valid, but this parts were mainly written by @jnugh

**Review by svenseeberg — COMMENTED** [review]
Can't formally approve, because I started this PR ;-) I picked about 10 random files and checked the comments. I could not find issues.

**Review by timoludwig — APPROVED** [review]
Ok, I'll approve the PR instead. Since this are only changes to docstrings, small mistakes are tolerable. If we find errors in the future, we can still improve it.

**Pull request merged**
