### PR TITLE
Refactor forms and permissions

### PR DESCRIPTION
**Pull request by timoludwig**
### Short description

I refactored both the backend and the frontend of the forms and added more fine-graded permissions

### Proposed changes

- Centralized CSS for form fields
  - Add [@tailwindcss/forms](https://github.com/tailwindlabs/tailwindcss-forms) plugin for decent base styling
  - Put additional styling in the stylesheet
  - Remove duplicated css classes in html code
  - Make form styling more consistent
- Add support for staff and non-staff roles
  - Add dedicated Role model with one to one mapping to `django.contrib.auth.models.Group`
  - Add boolean field `staff_role`
- Refactor forms
  - Set additional instance attributes in `CustomModelForm`
- Refactor Permissions
  - Use more fine-graded permissions for all models
  - Use inbuilt permissions where possible
  - Check for permissions instead of superuser/staff status

### Resolved issues

Fixes (partially): #172
Fixes: #684
Fixes: #696
Fixes: #729

### CODE REVIEW

**Comment by timoludwig** [comment]
I'm aware that this PR cannot be reviewed in detail. But I suggest to do a superficial review and merge this PR soon anyway instead of leaving it open for weeks until somebody finds the time to check it extensively...

**Review by melegiul — CHANGES_REQUESTED** [review]
Awesome, getting rid of some css classe sounds like a great plan :rocket: 
But there is one thing I stumbled over on my system, just concerning the test data fixtures.
Locally running the tests fails due to HTTP 403 code in seven cases (all located in RegionViewTest):
Screenshot from 2021-07-02 20-05-43
One way to let tests succeed is to extend the permissions of our test user with the role "management" by adding to `src/cms/fixtures/roles.json`:
- 'Can view media file' (46)
- 'Can view page' (22)
- 'Can view location' (27)

But I wonder why circleci is not detecting this permission problem :thinking:

**Comment by timoludwig** [comment]
> One way to let tests succeed is to extend the permissions of our test user with the role "management" by adding to `src/cms/fixtures/roles.json`
>
> But I wonder why circleci is not detecting this permission problem thinking

Actually, the management role on this branch has this permission already, but unfortunately permissions are changing their ids each time the database changes, so for now there is no way of persisting these in an existing database.
To fix the permissions on your machine locally, you have to execute `./dev-tools/prune_database.sh` before loading the new roles fixture. In the future, this problem will be fixed by resolving issue #748.

**Review by melegiul — APPROVED** [review]
Thank you very much, I was not aware of this issue so pruning the database worked for me :tada:

**Pull request merged**
