### PR TITLE
Show the correct url when clicking on a node that is a child of a link

### PR DESCRIPTION
**Pull request by david-venhoff**
### Short description
This pr fixes the tinymce link popup to show the correct url when the selected element is just a child of a link.

### Proposed changes
- Make the `getAnchor` function walk the node hierarchy until it finds an anchor element

### Resolved issues
Fixes: #912

### CODE REVIEW

**Review by timoludwig — APPROVED** [review]
Thanks, this fixes the issue! :+1:

I noticed one problem when I select an image and use the custom link pugin to create a link with this image via "Insert -> Link", it replaces the image with the link text... but I'm not sure how the original link plugin handled this case and I don't think it's related to this issue/PR.

**Comment by david-venhoff** [comment]
I just checked and the original link plugin handled this case correctly, by only changing the parent elements url. I think it makes sense to include that in this pr for consistency, but I can also open a new issue and make a separate pr. What do you think?

**Comment by timoludwig** [comment]
> I just checked and the original link plugin handled this case correctly, by only changing the parent elements url. I think it makes sense to include that in this pr for consistency, but I can also open a new issue and make a separate pr. What do you think?

I think both is fine, do whatever you prefer.

**Comment by david-venhoff** [comment]
Now the text field in the link popup is disabled if the current link contains anything else other than text, because the popup can only handle text. This also includes simple styling, for example editing a link with a cursive word disables the text field. 
Also clicking `unlink` on a link that has nested elements should keep those elements and only delete the link itself now.

**Review by timoludwig — APPROVED** [review]
Amazing, works like a charm! :+1:

**Pull request merged**
