### PR TITLE
Improve hierarchy in page tree

### PR DESCRIPTION
**Pull request by timoludwig**
### Short description

This adds improvements to the hierarchy of the page tree.

### Proposed changes

- Clarify hierarchy in page tree
- Enable collapsing of subpages

### Resolved issues

Fixes: #503

Screenshot_2021-02-12 Integreat CMS

### CODE REVIEW

**Review by melegiul — APPROVED** [review]
Awesome, works like a charm.:tada:
There just one topic rather for discussion. I found that at level 3 or greater the row height of a page grows, but whether this is a problem depends on how many hierarchy levels are expected. Maybe we could increase the hierarchy columns max-width a bit. 
page-hierarchie

**Comment by timoludwig** [comment]
Even with many levels, this looks fine for me:
Screenshot_2021-02-19 Integreat CMS

Can you check whether your dependencies (especially tailwindcss) are up to date? The css class `whitespace-nowrap` was added recently and should in theory make it impossible for the two icons to wrap into a new line.

**Comment by ulliholtgrave** [comment]
I couldn't reproduce it, too. I tried it with multiple levels, on firefox & chrome, on two different screens and with different resolutions. Still seems to work.
grafik

**Comment by melegiul** [comment]
> Even with many levels, this looks fine for me:
> Screenshot_2021-02-19 Integreat CMS
> 
> Can you check whether your dependencies (especially tailwindcss) are up to date? The css class `whitespace-nowrap` was added recently and should in theory make it impossible for the two icons to wrap into a new line.

Ok, then this problem just exists on my side, I will check my dependencies. It was my fault, sorry for that.

**Comment by timoludwig** [comment]
> Ok, then this problem just exists on my side, I will check my dependencies. It was my fault, sorry for that.

No worries, since we want to support all more or less modern browsers, it would be still an issue if the problem persisted on your system.

**Comment by melegiul** [comment]
> No worries, since we want to support all more or less modern browsers, it would be still an issue if the problem persisted on your system.

So I found that the problem still exists on Firefox (version 85.0.1 which should be the latest), but I just tried to reproduce on Chrome and there all is fine, so this might be a problem related to firefox.

**Comment by melegiul** [comment]
I also checked my tailwind installation and `npm list` gave me, that there is version `2.0.3` installed. Which one is yours?

**Comment by melegiul** [comment]
But I'm still wondering why on @ulliholtgrave firefox everything is fine also.

**Comment by timoludwig** [comment]
> I also checked my tailwind installation and `npm list` gave me, that there is version `2.0.3` installed. Which one is yours?

I've also installed tailwind version `2.0.3` as defined in package.json: https://github.com/Integreat/integreat-cms/blob/63dccd6fbe99a3857681d82d211557406e47d0c6/package.json#L39
And my Firefox is just a minor version ahead (85.0.2), so this shouldn't make the difference...

Maybe it's a caching issue? Can you clear your cache and reload?

**Comment by melegiul** [comment]
> I've also installed tailwind version `2.0.3` as defined in package.json:
> 
> https://github.com/Integreat/integreat-cms/blob/63dccd6fbe99a3857681d82d211557406e47d0c6/package.json#L39

Yes, I cleared the cache and now it works on my firefox, too. Thanke you:tada:

**Pull request merged**
