### PR TITLE
Always return JSON in API

### PR DESCRIPTION
**Pull request by timoludwig**
### Short description

This adds a custom decorator which makes sure the API always returns a JSON response, even if the error `Http404` is raised.

### Proposed changes

- Make use of shortcut functions in API
- Add json_response decorator

### Resolved issues

Fixes: #578

### CODE REVIEW

**Review by melegiul — COMMENTED** [review]
Works like expected, but I got one question. When I try the url: api/augsburg/de-de/imprint I got a RelatedObjectDoesNotExist exception. Should the decorator transform this messages also to JSON?

**Comment by timoludwig** [comment]
> Works like expected, but I got one question. When I try the url: api/augsburg/de-de/imprint I got a RelatedObjectDoesNotExist exception. Should the decorator transform this messages also to JSON?

I guess we should rather use e.g. `get_object_or_404(region.imprint)` in the imprint api to make sure it throws a `Http404` instead of `RelatedObjectDoesNotExist`. This way, we are consistent to the other endpoints and don't need special error handling for other exceptions. I will add this to the first commit of this PR.

**Comment by timoludwig** [comment]
Actually, I changed my mind about this: Probably, it makes sense to just return an empty response in case the imprint doesn't exist instead of an error. At least this is the current behavior of the WordPress APIv3.

**Review by melegiul — APPROVED** [review]
Ok, looks good to me. I found another problem with the url: api/augsburg/de-de/offers, here we got a TypeError Exception, but I don't thinks that's related to the decorator.

**Comment by timoludwig** [comment]
> Ok, looks good to me. I found another problem with the url: api/augsburg/de-de/offers, here we got a TypeError Exception, but I don't thinks that's related to the decorator.

Thanks for reporting! It took me a moment to figure out what's going on there. It turns out, the OR-clauses in the urls.py `(offers|extras)` were captured as regex-match and thus the string "offers" was treated like another parameter which is passed to the view. I fixed this by using the syntax for non-capturing regex groups: `(?:offers|extras)`.

**Pull request merged**
