### PR TITLE
Refactor developer tools

### LINKED ISSUE #531: Add shellcheck to circleci workflow
### Motivation

The bash scripts in our repository are currently not part of any code style or correctness checks.

### Proposed Solution

We could add the tool [shellcheck](https://www.shellcheck.net/) to change this. Fortunately, it has already a pre-built [circleci orb](https://circleci.com/developer/orbs/orb/circleci/shellcheck) which can be easily added to our workflow. The specified directoy  of the job should be `dir: ./dev-tools`.

### Additional Context

Depending on the kind of errors/warnings the tool produces, the [dev-tools](https://github.com/Integreat/cms-django/tree/develop/dev-tools) might need a few changes to make them initially conform to shellcheck's standards.

### LINKED ISSUE #633: Check for docker group in run.sh
### Motivation

The run.sh dev tool requires sudo permissions to connect to the docker daemon. If the user is part of the docker group, this is technically not necessary. 

### Proposed Solution

Check if the user is in the docker group and only restart the script with sudo if the user is not.

### PR DESCRIPTION
**Pull request by timoludwig**
### Short description

I completely refactored the dev tools to avoid code duplications and implement some improvements.

### Proposed changes

- Check for `pipenv` version in install.sh
  - Require at least `pipenv` version `2018.10.9`
  - Move requirement checks for `netcat`, `gettext` and `pcregrep` to `install.sh`
- Outsource dev-tool functions to separate file
- Refactor dev tools 
  - Reduce code duplication by defining more re-usable functions
  - Terminate scripts if an error occurs
  - Add options `--verbose` and `--help` to all dev tools
  - Add option `--pre-commit` to install.sh
  - Add option `--fast` to run.sh
  - Add more verbose and colorized output :heart_eyes: 
- Check if root privileges are required in dev tools (fixes #633)
  - Before asking for root permissions, check if the user is in the docker group which means that the user can access the docker daemon without sudo permissions
- Add shellcheck (fixes #531)
  - Add shellcheck to dev dependencies
  - Add shellcheck pre-commit hook
  - Add shellcheck CircleCI job
  - Make dev-tools shellcheck compliant

### Resolved issues

Fixes: #531 Add shellcheck to circleci workflow
Fixes: #633 Check for docker group in run.sh

### CODE REVIEW

**Comment by ulliholtgrave** [comment]
Seems like the PR isn't building accordingly :thinking:

**Comment by timoludwig** [comment]
> Seems like the PR isn't building accordingly :thinking:

I think this is due to a bug in the [CircleCI shellcheck orb](https://circleci.com/developer/orbs/orb/circleci/shellcheck). I opened an issue (https://github.com/CircleCI-Public/shellcheck-orb/issues/38) and an upstream PR (https://github.com/CircleCI-Public/shellcheck-orb/pull/39) for it.

Until the maintainers find the time to review my contribution, I think this PR is also ready for review even if the shellcheck is still failing. The commit 09a507700c458de2ebeea92db819bfb7552e6cc9 (shellcheck circleci test) however is just a debugging test and will be removed when the upstream shellcheck orb is fixed, so these changes to the circle config do not require a review.

**Review by ulliholtgrave — APPROVED** [review]
Thanks for the PR. This really improves our development context :👍

**Review by ulliholtgrave — APPROVED** [review]
Thanks for the PR. This really improves our development context :👍

**Pull request merged**
