### PR TITLE
Check permissions for menu items

### PR DESCRIPTION
**Pull request by timoludwig**
### Short description

Only show menu item if user has permission to open it

### Resolved issues

Fixes: #676

### CODE REVIEW

**Comment by ulliholtgrave** [comment]
So far, our role "Redakteur" isn't able to see the menu item "pages". As I wasn't able to grant the user specific "per page" permissions this role is now pretty limited.

**Comment by timoludwig** [comment]
> So far, our role "Redakteur" isn't able to see the menu item "pages". As I wasn't able to grant the user specific "per page" permissions this role is now pretty limited.

I changed the `view_pages` permission in PR #656, thus I didn't bother to fix it here for the Redakteur role.

**Review by ulliholtgrave — APPROVED** [review]
Well, besides the "Redakteur" stuff, everything works as promised. I'll try it on develop, when we merged the PR :)

**Comment by timoludwig** [comment]
> Well, besides the "Redakteur" stuff, everything works as promised. I'll try it on develop, when we merged the PR :)

I had to resolve the conflicts anyway, so you can also check it again if you want :smile:

**Pull request merged**
